name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Xcode Select
      run: sudo xcode-select -switch /Applications/Xcode_13.2.app

    - name: Build and Test
      run: xcodebuild clean build test -project Valkyrie.xcodeproj -scheme "Valkyrie" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
